### ISSUE TITLE
Item Wont Load In Game 1.18

### ISSUE THREAD

**Issue by aalopz2011** [dannydjdk/Ranged-Wireless-Redstone#3] opened 2021-12-04 20:17 UTC
When I search Transmitter or Receiver it wont show up I also tried to go in the redstone tab but its still not there.

**Comment by dannydjdk** [comment] 2021-12-06 14:40
Items for this mod appear in their own creative tab, not the vanilla redstone tab. If you are not seeing that tab, please provide more details, such as the forge version you are using, what launcher you're using, how you installed forge, what other mods are installed, etc. If possible, screenshots of the splash screen, mods folder and creative tabs are also helpful.

Of course, I tested this mod and it worked in my environment, so I want to figure out what is different in your setup compared to mine.

**Comment by dannydjdk** [comment] 2021-12-20 06:41
Closing this issue since I can not reproduce it and haven't received a response.
If this continues to be a problem, please provide details, and I'll reopen this.

**Closed by dannydjdk** 2021-12-20 06:41 UTC
